
version: '2'

services:
   postgres:
      image: postgres:12
      environment:
         - POSTGRES_PASSWORD:test
      ports:
         - "54320:5432"

   pdm-backend:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      links:
         - "postgres:postgres"
      environment:
         - DB_HOST=postgres
         - DB_PASSWORD=test
         - DB_USER=postgres
         - SECRET_KEY_BASE=${SECRET_KEY_BASE}
         - RAILS_LOG_TO_STDOUT=true
